from datetime import datetime
from textwrap import dedent

from agno.agent import Agent
from agno.tools.exa import ExaTools

from agno.models.openai import OpenAIChat
import os
import sys
project_root = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
sys.path.insert(0, project_root)

from config.settings import Settings


#Verify the env variables
settings = Settings()
settings.validate()

academic_research_agent = Agent(
    model=OpenAIChat(id="gpt-4o", api_key=settings.openai_api_key),
    tools=[
        ExaTools(
            start_published_date=datetime.now().strftime("%Y-%m-%d"), type="keyword"
        )
    ],
    description=dedent("""\
        You are a seasoned academic researcher with multidisciplinary expertise.
        Your scholarly skills include: 📚

        - Rigorous research design and methodology
        - Integration across diverse fields
        - Critical review of scholarly literature
        - Scientific writing and publication skills
        - Expertise in peer review processes
        - Effective citation and bibliography management
        - Data analysis and interpretation
        - Clear technical communication
        - Upholding research ethics
        - Tracking emerging academic trends\
    """),
    instructions=dedent("""\
        Step 1: Literature Search 🔍
        - Perform at least 3 independent academic database queries
        - Focus on peer-reviewed journals and reputable sources
        - Highlight cutting-edge findings and recent breakthroughs
        - Identify leading scholars and key research institutions

        Step 2: Analytical Synthesis 📊
        - Integrate and compare findings across multiple studies
        - Critically assess research methods and validity
        - Identify areas of agreement and ongoing debates
        - Evaluate real-world or theoretical implications

        Step 3: Structured Reporting 📝
        - Compose a clear and engaging academic title
        - Write an abstract summarizing key insights
        - Detail the research methodology explicitly
        - Present findings in a logical and coherent order
        - Formulate evidence-based conclusions

        Step 4: Academic Rigor ✓
        - Ensure all sources are correctly cited
        - Maintain objective and balanced perspectives
        - Highlight directions for future research
        - Uphold the highest standards of academic integrity\
    """),
    expected_output=dedent("""\
        # {Academic Title} 📚

        ## Abstract
        {Brief summary of research objectives and principal findings}

        ## Introduction
        {Background and importance of the topic}
        {Goals and scope of the research}

        ## Methodology
        {Search approach and criteria}
        {Data selection methods}

        ## Literature Review
        {Current research landscape}
        {Significant discoveries and trends}

        ## Analysis & Discussion
        {Evaluation of evidence}
        {Comparison across studies}
        {Identified research gaps}

        ## Future Perspectives
        {Potential avenues for further research}
        {Practical applications}
        {Open challenges}

        ## Conclusions
        {Summary of main insights}
        {Broader implications}

        ## References
        {Accurate and formatted academic citations}

        ---
        Research generated by AI Academic Researcher
        Publication Date: {current_date}
        Last Revised: {current_time}\
    """),
    markdown=True,
    show_tool_calls=True,
    add_datetime_to_instructions=True,
    save_response_to_file="tmp/{message}.md",
)

# Example call
if __name__ == "__main__":
    academic_research_agent.print_response(
        "Provide a comprehensive review on recent innovations in quantum computing hardware",
        stream=True,
    )

# Additional research topics suggestions:
"""
Quantum Computing:
1. "Review advances in quantum error mitigation techniques"
2. "Analyze hardware architectures for scalable quantum computers"
3. "Study applications of quantum algorithms in chemistry"
4. "Explore quantum sensor technologies and their uses"

Biotech & Medicine:
1. "Assess progress in mRNA-based therapies"
2. "Investigate organ-on-chip models for drug testing"
3. "Review developments in personalized cancer treatment"
4. "Analyze breakthroughs in brain-computer interfaces"

Materials Science:
1. "Evaluate recent innovations in nanomaterials"
2. "Study properties of novel 2D materials"
3. "Investigate advances in self-healing polymers"
4. "Review improvements in solid-state battery technologies"

Artificial Intelligence:
1. "Survey recent progress in large language models"
2. "Examine emerging trends in AI interpretability"
3. "Analyze neuromorphic computing architectures"
4. "Explore safety and ethical challenges in AI development"
"""
