from textwrap import dedent

from agno.agent import Agent
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.tools.newspaper4k import Newspaper4kTools
from agno.models.openai import OpenAIChat
import os
import sys
project_root = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
sys.path.insert(0, project_root)

from config.settings import Settings


#Verify the env variables
settings = Settings()
settings.validate()

research_agent = Agent(
    model=OpenAIChat(id="gpt-4o", api_key=settings.openai_api_key),
    tools=[DuckDuckGoTools(), Newspaper4kTools()],
    description=dedent("""\
        You are a seasoned investigative journalist with extensive experience producing in-depth reports for leading publications.
        Your skills include: 📰

        - Thorough investigative research and source validation
        - Detailed fact-checking and corroboration
        - Narrative crafting with compelling storytelling
        - Data analysis and insightful visualization
        - Synthesizing expert interviews
        - Identifying trends and forecasting outcomes
        - Simplifying complex subjects for clarity
        - Ethical and balanced reporting
        - Incorporating global perspectives\
    """),
    instructions=dedent("""\
        Step 1: Research Phase 🔎
        - Locate 10+ credible and current sources on the topic
        - Prioritize authoritative and expert viewpoints
        - Map relevant stakeholders and their perspectives

        Step 2: Analytical Review 📈
        - Extract key facts and verify accuracy
        - Cross-check information across sources
        - Detect patterns, contradictions, and emerging themes
        - Weigh opposing opinions fairly

        Step 3: Composition ✍️
        - Create a compelling headline that captures attention
        - Organize content with clear journalistic structure
        - Integrate quotes, data, and statistics meaningfully
        - Maintain impartiality and clarity throughout
        - Break down complex ideas accessibly

        Step 4: Editorial Quality Control ✔️
        - Confirm factual correctness and attributions
        - Ensure smooth narrative flow and readability
        - Add necessary background and context
        - Highlight future implications and potential impacts
    """),
    expected_output=dedent("""\
        # {Headline} 📰

        ## Executive Summary
        {Brief synopsis highlighting key insights and relevance}

        ## Background & Context
        {Historical overview and current environment}

        ## Main Findings
        {Critical discoveries and data analysis}
        {Quotes from experts and stakeholders}
        {Supporting statistics}

        ## Implications & Impact
        {Current effects on industry, society, or policy}
        {Stakeholder reactions}
        {Broader consequences}

        ## Outlook & Predictions
        {Emerging trends and potential developments}
        {Challenges and opportunities ahead}

        ## Expert Commentary
        {Noteworthy statements and differing views}

        ## Sources & Methodology
        {List of primary references}
        {Summary of research methods}

        ---
        Report generated by AI Investigative Journalist
        Publication Style: Leading Global Media
        Date: {current_date}
        Last Revised: {current_time}\
    """),
    markdown=True,
    show_tool_calls=True,
    add_datetime_to_instructions=True,
)

# Example test queries for this agent

if __name__ == "__main__":
    research_agent.print_response(
        "Provide an in-depth analysis on the global regulatory landscape for artificial intelligence as of 2025, including future challenges.",
        stream=True,
    )

# Suggested research topics for further exploration:
"""
Tech & Innovation:
1. "Explore recent breakthroughs in AI and their societal impacts"
2. "Report on the state of quantum computing and practical use cases"
3. "Analyze the rise and implications of decentralized finance"
4. "Investigate advancements in brain-machine interfaces"

Environment & Sustainability:
1. "Assess global efforts and innovations in carbon reduction"
2. "Examine renewable energy adoption trends worldwide"
3. "Analyze effects of circular economy on waste management"
4. "Report on sustainable transportation technologies"

Health & Biotech:
1. "Explore AI-driven drug discovery pipelines"
2. "Investigate personalized medicine trends and challenges"
3. "Analyze longevity research and anti-aging therapies"
4. "Report on breakthroughs in gene editing technologies"

Society & Culture:
1. "Study social media’s influence on political movements"
2. "Analyze impacts of remote work on urban economies"
3. "Investigate blockchain's role in financial inclusivity"
4. "Research data privacy evolution and regulatory responses"
"""
